apiVersion: apps/v1
kind: Deployment
metadata:
  name: segment
spec:
  selector:
    matchLabels:
      app: segment
  template:
    metadata:
      labels:
        app: segment
    spec:
      containers:
      - name: segment
        image: 740446032364.dkr.ecr.us-west-2.amazonaws.com/mlzoomcamp-images:blood-vessel-seg-v1
        resources:
          limits:
            memory: "2G"
            cpu: "500m"
        ports:
        - containerPort: 80